In [2]:
import numpy as np

In [3]:
# Creating a array
variable_name = [1, 2, 3, 4, 5]
# Printing the array
print(variable_name)
# Printing the type of the array
print(type(variable_name))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
# Converting the array to a numpy array
new_variable = np.array(variable_name)
# Printing the numpy array
print(new_variable)
# Printing the type of the numpy array
print(type(new_variable))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Creating a 2D array
python_2d_array = [[9000, 2137, 21, 63, 9001], [67, 41, 666, 69, 34], [43, 61, 56, 420, 20]]
# Printing the 2D array
print(python_2d_array)
# Printing the type of the 2D array
print(type(python_2d_array))

[[9000, 2137, 21, 63, 9001], [67, 41, 666, 69, 34], [43, 61, 56, 420, 20]]
<class 'list'>


In [6]:
# Converting the 2D array to a numpy array
numpyArray = np.array(python_2d_array)
# Printing the numpy array
print(numpyArray)
# Printing the type of the numpy array
print(type(numpyArray))

[[9000 2137   21   63 9001]
 [  67   41  666   69   34]
 [  43   61   56  420   20]]
<class 'numpy.ndarray'>


In [7]:
# Creating an array that contains the numbers from 0 to 14 with a step of 2
np.arange(0, 15 ,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [8]:
# Creating an array that contains the numbers from 0 to 15 that is reshaped into a 3 by 5 array
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# Creating an array that contains 15 zeros
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Creating an array that contains 15 zeros that is reshaped into a 3 by 5 array
np.zeros(15).reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Creating an array that contains 15 ones
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# Creating an array that contains 15 ones that is reshaped into a 3 by 5 array
np.ones(15).reshape(3, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Creating an array that contains 9 zeros that is reshaped into a 3 by 3 array with the data type of int
np.zeros(9, dtype=int).reshape(3, 3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
# Creating an array that contains the identity matrix of size 5 by 5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Creating an array that contains 20 random integers from 0 to 100 that is reshaped into a 4 by 5 array
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[23, 50, 70, 63, 44],
       [21, 40, 86, 20, 57],
       [66, 54, 17, 30, 92],
       [96, 15, 92, 67, 29]], dtype=int32)

In [16]:
# Printing the smallest and largest values in the array A, and their positions
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 15, and is a located at position 16
The largest value in A is 96, and is a located at position 15


In [17]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
# Addition each element in array A with the corresponding element in array B
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [19]:
# Adding 5 to each element in array A
A + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
# Subtracting each element in array B from the corresponding element in array A
A - B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [21]:
# Subtracting 5 from each element in array A
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Multiplying each element in array A with the corresponding element in array B
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [23]:
# Multiplying each element in array A with 5
A * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [24]:
# Dividing each element in array A with the corresponding element in array B
A / B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [25]:
# Dividing each element in array A by 2
A / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

In [26]:
# Finds whatever element in array F is even, it will be multiplied by -1, and if it is odd, it will be multiplied by 100
np.where(F%2==0, -F, F*100)

array([  0, 100,  -2, 300,  -4, 500,  -6, 700,  -8, 900, -10])

In [27]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
# Printing the first, sixth, and fifteenth element in array A
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


In [29]:
# Changing the first five elements in array A to 0
A[0:5] = 0
A

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
# Printing the 0th row and 2nd column, 3rd row and 3rd column, and 4th row and 2nd column in array B
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


In [32]:
# Getting the first two rows and the and columns 6-7 in array B
B[0:2, 4:6]

array([[ 4,  5],
       [14, 15]])

In [33]:
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [34]:
# Creating a boolean array that is True where the elements in array C are divisible by 3, and False otherwise
C%3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False]])

In [35]:
# Counting how many elements in array C are divisible by 3
(C%3 == 0).sum()

np.int64(17)